# -*- coding: utf-8 -*-
"""LC August: Find All Duplicates in an Array.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n7hFJsKAsVVqRa79qrjU7DINrIkJRwxR
"""

class Solution:
    def findDuplicates(self, nums: List[int]) -> List[int]:
          
            # Creating an empty dictionary  
            count = {} 
            repeat = []
            
            for i in nums: 
                count[i] = count.get(i, 0) + 1
            
            for k,v in count.items():
                if v>1:
                    repeat.append(k)
            
            return repeat