# -*- coding: utf-8 -*-
"""LC #1480 Running Sum of 1d Array.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aIHO6lB5Cwaa5nlDYwEQPPJI7GHEK9Ak
"""

class Solution(object):
    def runningSum(self, nums):     
        n = len(nums)
        result = list()
        
        if n == 0: return result
		
        currentSum = 0
        for i in range(n):
            currentSum += nums[i]
            result.append(currentSum)
        
        return result